### ISSUE TITLE
No retry after game over

### ISSUE THREAD

**Issue by GAumala** [taniarascia/snek#2]
Hello, this looks really cool, I had fun playing with it this morning. Also I read the source and it's very well written, great organization and super easy to read. Great job!

I wish the game had a retry option after the game over screen. Maybe the `Game` class could expose a `reset()` method so that it can be called after pressing enter on the game over screen?

**Comment by taniarascia** [comment]
Excellent! Yes, I was going to add that in today. Thanks for playing and the compliment! :)

**Comment by taniarascia** [comment]
Fixed!
