### ISSUE TITLE
The snake doesn't get longer

### ISSUE THREAD

**Issue by svenvarkel** [taniarascia/snek#5]
First - it's a pretty cool game!

It seems to me that the snake doesn't grow after eating the red dots. Shouldn't it grow?:)

**Comment by taniarascia** [comment]
Are you sure? How many red dots did you try eating? Since pixels in the terminal are twice as long as they are wide, you’d have to eat a few before you noticed it looking longer.

**Comment by taniarascia** [comment]
Since I can’t replicate this, I’m going to close the issue.

**Comment by svenvarkel** [comment]
Hi, I guess you're right and that's exactly the issue 😃

Take care,
Sven
