### ISSUE TITLE
Game over when it shouldn't

### ISSUE THREAD

**Issue by corlaez** [taniarascia/snek#8]
When snek is going horizontally to the right
and you quickly (very quickly try faster if you couldn't reproduce it) type: "DOWN ARROW" AND THEN "LEFT ARROW"
The snek seems to collide into itself horizontally (it didn't manage to go down before going to the left)

Expected: 
->->->->||
.............<-

Instead I get:
->->->-><-   (Game over snek collided into itself horizontally)

**Comment by taniarascia** [comment]
I had a fix for this but I took it out because I thought it got fixed. Turns out I just made the speed faster and it happened less frequently 😬 I can bring it back.

**Comment by taniarascia** [comment]
This issue should be fixed now.

**Comment by MartinRosenberg** [comment]
I was playing the game via `npx` and also discovered this bug; I don't think you published the fix to npm.
